<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ec56617b-e842-4b54-8da4-52447d95d552</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="InventoryERP.Api\**\*.cs" />
    <Compile Remove="NVGInventory.Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="InventoryERP.Api\**" />
    <Content Remove="NVGInventory.Tests\**" />
    <Content Remove="frontend\**" />
    <Content Remove="**\bin\**" />
    <Content Remove="**\obj\**" />
    <None Remove="InventoryERP.Api\**" />
    <None Remove="NVGInventory.Tests\**" />
    <None Remove="frontend\**" />
    <None Remove="**\bin\**" />
    <None Remove="**\obj\**" />
  </ItemGroup>

</Project>
