import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, ArrowLeft, Camera, CheckCircle2, ChevronDown, Clock, Eye, FileUp, MapPin, Navigation, Truck } from "lucide-react";
import EmptyState from "@/components/EmptyState";
import LoadingSkeleton from "@/components/LoadingSkeleton";
import PageHeader from "@/components/PageHeader";
import StatusBadge from "@/components/StatusBadge";
import ToastHost from "@/components/ToastHost";
import TripMap from "@/components/dispatch/TripMap";
import { Button } from "@/components/ui/button";
import { api, apiOptional } from "@/lib/api";
import { captureDocumentPhoto } from "@/lib/camera";
import { useToast } from "@/lib/useToast";
import { Capacitor } from "@capacitor/core";
import {
  canDriverUploadDocument,
  formatDocumentLabel,
  formatDocumentStateLabel,
  getDeliveryDocumentBlockers,
  getDocumentState,
  getDriverTripNextAction,
  isDocumentAttentionState
} from "./driverTripUi";
import type { DispatchTripDetail, GeneratedWaybill, TripDocumentType, TripStatus } from "./types";

const visibleDocumentTypes: TripDocumentType[] = ["ATW", "EIR", "GATE_PASS", "DR", "POD", "WAYBILL"];
const driverHoldEligible: TripStatus[] = ["ENROUTE_PICKUP", "AT_PICKUP", "LOADED", "ENROUTE_DROPOFF", "AT_DROPOFF"];
const failedAttemptEligible: TripStatus[] = ["ENROUTE_PICKUP", "AT_PICKUP", "ENROUTE_DROPOFF", "AT_DROPOFF"];

const driverActionMap: Record<TripStatus, { endpoint: string; label: string } | null> = {
  DRAFT: null,
  READY_FOR_DISPATCH: null,
  DISPATCHED: { endpoint: "start", label: "Start trip to pickup" },
  ENROUTE_PICKUP: { endpoint: "arrive-pickup", label: "Mark arrived at pickup" },
  AT_PICKUP: { endpoint: "confirm-loaded", label: "Confirm container loaded" },
  LOADED: { endpoint: "depart-pickup", label: "Start trip to drop-off" },
  ENROUTE_DROPOFF: { endpoint: "arrive-dropoff", label: "Mark arrived at drop-off" },
  AT_DROPOFF: { endpoint: "confirm-delivery", label: "Confirm delivery" },
  DELIVERED: null,
  CLOSED: null,
  CANCELLED: null,
  ON_HOLD: null,
  FAILED_ATTEMPT: null
};

type ActionModal = { type: "HOLD" | "FAILED"; remarks: string; eventAt: string } | null;

function formatDateTime(value?: string | null) {
  if (!value) return "Not scheduled";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "Not scheduled";
  return new Intl.DateTimeFormat(undefined, {
    month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit"
  }).format(date);
}

function toLocalInput(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  const pad = (number: number) => String(number).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function getErrorMessage(error: unknown, fallback: string) {
  return error instanceof Error ? error.message : fallback;
}

function getDocumentHint(type: TripDocumentType, status: TripStatus, state: string, hasWaybill: boolean) {
  if (type === "ATW") {
    return state === "VERIFIED" ? "Verified by dispatch." : "Managed by dispatch. Contact dispatch if this needs attention.";
  }
  if (type === "WAYBILL") return hasWaybill ? "Generated by dispatch." : "Generated by dispatch when available.";
  if ((type === "EIR" || type === "GATE_PASS") && !["AT_PICKUP", "LOADED", "ENROUTE_DROPOFF", "AT_DROPOFF", "DELIVERED", "CLOSED"].includes(status)) return "Available after arriving at pickup.";
  if (type === "DR" && !["AT_DROPOFF", "DELIVERED", "CLOSED"].includes(status)) return "Available after arriving at drop-off.";
  if (type === "POD" && !["AT_DROPOFF", "DELIVERED", "CLOSED"].includes(status)) return "Available after arriving at drop-off.";
  if (type === "POD" && status === "AT_DROPOFF" && state === "MISSING") return "Upload before confirming delivery.";
  if (state === "REJECTED") return "This copy was rejected. Upload a clear replacement.";
  if (state === "UPLOADED") return "Waiting for dispatcher verification.";
  return null;
}

export default function MyTripDetailPage() {
  const { id } = useParams();
  const nav = useNavigate();
  const { toasts, show } = useToast();
  const [loading, setLoading] = useState(true);
  const [trip, setTrip] = useState<DispatchTripDetail | null>(null);
  const [waybill, setWaybill] = useState<GeneratedWaybill | null>(null);
  const [pendingAction, setPendingAction] = useState(false);
  const [modal, setModal] = useState<ActionModal>(null);
  const fileInputs = useRef<Partial<Record<TripDocumentType, HTMLInputElement | null>>>({});
  const isNative = Capacitor.isNativePlatform();

  const fetchTrip = async () => {
    if (!id) return;
    try {
      setLoading(true);
      const detail = await api<DispatchTripDetail>(`/api/dispatch/my-trips/${id}`, { method: "GET" });
      setTrip(detail);
      setWaybill(await apiOptional<GeneratedWaybill>(`/api/dispatch/trips/${id}/waybill`, { method: "GET" }));
    } catch (error: unknown) {
      show(getErrorMessage(error, "Unable to load this trip."), "error");
      setTrip(null);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { void fetchTrip(); }, [id]);

  const stops = useMemo(() => ({
    pickup: trip?.stops.find((stop) => stop.stopType === "PICKUP") ?? null,
    dropoff: trip?.stops.find((stop) => stop.stopType === "DROPOFF") ?? null
  }), [trip]);
  const nextAction = trip && trip.status === "AT_DROPOFF" && getDeliveryDocumentBlockers(trip.documents).length > 0
    ? null
    : trip
      ? driverActionMap[trip.status]
      : null;

  const submitAction = async (endpoint: string, remarks?: string) => {
    if (!trip) return;
    try {
      setPendingAction(true);
      await api(`/api/dispatch/trips/${trip.id}/${endpoint}`, {
        method: "POST",
        body: JSON.stringify({ eventAt: new Date().toISOString(), rowVersion: trip.rowVersion, remarks: remarks ?? null })
      });
      show("Trip updated.", "success");
      await fetchTrip();
    } catch (error: unknown) {
      show(getErrorMessage(error, "The trip changed elsewhere. Refresh and try again."), "error");
      await fetchTrip();
    } finally {
      setPendingAction(false);
    }
  };

  const uploadDocument = async (type: TripDocumentType, file: File) => {
    if (!trip) return;
    try {
      setPendingAction(true);
      // The current API accepts the storage key; preserve that contract until file-storage upload is expanded.
      await api(`/api/dispatch/trips/${trip.id}/documents`, { method: "POST", body: JSON.stringify({ type, storageKey: file.name }) });
      show("Document uploaded.", "success");
      await fetchTrip();
    } catch (error: unknown) {
      show(getErrorMessage(error, "Upload failed. Try again or choose another file."), "error");
    } finally {
      setPendingAction(false);
    }
  };

  const requestUpload = async (type: TripDocumentType) => {
    if (isNative) {
      try {
        const file = await captureDocumentPhoto();
        if (file) await uploadDocument(type, file);
      } catch (error: unknown) {
        show(getErrorMessage(error, "Camera is unavailable. Choose a file instead."), "error");
      }
      return;
    }
    fileInputs.current[type]?.click();
  };

  if (loading) return <div className="mx-auto max-w-5xl space-y-6"><PageHeader title="Trip details" description="Loading trip…" /><LoadingSkeleton rows={8} /></div>;
  if (!trip) return <EmptyState title="Trip not found" description="This trip could not be loaded. Return to your trips and try again." />;

  const atwState = getDocumentState(trip.documents, "ATW");
  const showAtwWarning = isDocumentAttentionState(atwState);
  const isException = trip.status === "ON_HOLD" || trip.status === "FAILED_ATTEMPT" || trip.status === "CANCELLED";
  const deliveryBlockers = trip.status === "AT_DROPOFF" ? getDeliveryDocumentBlockers(trip.documents) : [];
  const deliveryBlocked = trip.status === "AT_DROPOFF" && deliveryBlockers.length > 0;

  return (
    <div className="mx-auto max-w-5xl space-y-6 pb-28 md:pb-8">
      <ToastHost toasts={toasts} />
      <PageHeader
        title="Trip details"
        description={`Trip ${trip.id.slice(0, 8).toUpperCase()} · ${trip.customer?.name ?? "Customer"}`}
        breadcrumbs={<nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm"><Link className="text-muted-foreground hover:text-foreground" to="/dispatch/my-trips">My trips</Link><span className="text-muted-foreground">/</span><span className="font-mono text-foreground">{trip.id.slice(0, 8).toUpperCase()}</span></nav>}
        actions={<div className="flex gap-2"><Button variant="outline" onClick={() => nav("/dispatch/my-route-map")}><Navigation className="h-4 w-4" />Route map</Button><Button variant="outline" size="icon" onClick={() => nav("/dispatch/my-trips")} aria-label="Back to my trips"><ArrowLeft className="h-4 w-4" /></Button></div>}
      />

      <section className="surface-card overflow-hidden" aria-labelledby="trip-status-heading">
        <div className="flex flex-col gap-5 p-5 md:flex-row md:items-center md:justify-between md:p-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Current status</p>
            <div className="mt-2 flex flex-wrap items-center gap-2"><h2 id="trip-status-heading" className="font-mono text-xl font-bold">{trip.id.slice(0, 8).toUpperCase()}</h2><StatusBadge status={trip.status} /></div>
            <p className="mt-2 text-sm text-muted-foreground">{getDriverTripNextAction(trip)}</p>
          </div>
          {nextAction ? <Button className="hidden h-11 md:inline-flex" disabled={pendingAction} onClick={() => void submitAction(nextAction.endpoint)}><Navigation className="h-4 w-4" />{pendingAction ? "Updating…" : nextAction.label}</Button> : null}
          {deliveryBlocked ? <Button className="hidden h-11 md:inline-flex" disabled><Navigation className="h-4 w-4" />Confirm delivery</Button> : null}
        </div>
      </section>

      {showAtwWarning || isException ? (
        <section role="status" className={`flex items-start gap-3 rounded-2xl border px-4 py-3 text-sm ${isException ? "border-destructive/30 bg-destructive/10 text-destructive" : "border-amber-500/30 bg-amber-500/10 text-amber-800 dark:text-amber-200"}`}>
          <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" />
          <div><p className="font-semibold">{isException ? "Trip needs dispatch support" : "ATW needs dispatch attention"}</p><p className="mt-1 text-xs">{isException ? "This trip cannot advance until dispatch resolves the exception." : `ATW is ${formatDocumentStateLabel(atwState).toLowerCase()}. Drivers can view it but dispatch manages ATW uploads and verification.`}</p></div>
        </section>
      ) : null}

      {deliveryBlocked ? (
        <section role="status" className="flex items-start gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200">
          <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" />
          <div>
            <p className="font-semibold">Delivery is blocked until required documents are uploaded</p>
            <p className="mt-1 text-xs">{deliveryBlockers.join(" ")}</p>
          </div>
        </section>
      ) : null}

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_280px]">
        <div className="space-y-6">
          <section aria-labelledby="stops-heading" className="surface-card p-5 md:p-6">
            <div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Route progress</p><h2 id="stops-heading" className="mt-1 text-lg font-semibold">Scheduled stops</h2></div><Button variant="outline" size="sm" onClick={() => nav("/dispatch/my-route-map")}><Navigation className="h-4 w-4" />Open route</Button></div>
            <div className="space-y-5"><StopTimeline stop={stops.pickup} label="Pickup" current={trip.status === "DISPATCHED" || trip.status === "ENROUTE_PICKUP" || trip.status === "AT_PICKUP"} completed={["LOADED", "ENROUTE_DROPOFF", "AT_DROPOFF", "DELIVERED", "CLOSED"].includes(trip.status)} /><StopTimeline stop={stops.dropoff} label="Drop-off" current={["LOADED", "ENROUTE_DROPOFF", "AT_DROPOFF"].includes(trip.status)} completed={["DELIVERED", "CLOSED"].includes(trip.status)} /></div>
          </section>

          <section aria-labelledby="documents-heading" className="surface-card p-5 md:p-6">
            <div className="border-b border-border pb-4"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Document workflow</p><h2 id="documents-heading" className="mt-1 text-lg font-semibold">Required documents</h2><p className="mt-1 text-xs text-muted-foreground">Only documents available at this trip stage can be uploaded. A replacement supersedes the previous copy after server confirmation.</p></div>
            <div className="mt-4 space-y-3">
              {visibleDocumentTypes.map((type) => {
                const document = trip.documents.find((item) => item.type === type);
                const state = type === "WAYBILL" ? (waybill ? "READY" : "PENDING") : document?.state ?? "MISSING";
                const canUpload = canDriverUploadDocument(type, trip.status);
                const hint = getDocumentHint(type, trip.status, state, Boolean(waybill));
                return <DocumentRow key={type} type={type} state={state} hint={hint} canUpload={canUpload} pending={pendingAction} isNative={isNative} documentUrl={document?.storageKey} isWaybill={type === "WAYBILL" && Boolean(waybill)} onUpload={() => void requestUpload(type)} inputRef={(element) => { fileInputs.current[type] = element; }} onFile={(file) => void uploadDocument(type, file)} />;
              })}
            </div>
          </section>

          <section aria-labelledby="map-heading" className="space-y-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">Trip visibility</p><h2 id="map-heading" className="mt-1 text-lg font-semibold">Trip map</h2></div><TripMap pickup={{ latitude: stops.pickup?.latitude, longitude: stops.pickup?.longitude, label: stops.pickup?.locationText ?? "Pickup" }} dropoff={{ latitude: stops.dropoff?.latitude, longitude: stops.dropoff?.longitude, label: stops.dropoff?.locationText ?? "Drop-off" }} driver={trip.latestDriverLocation ? { latitude: trip.latestDriverLocation.latitude, longitude: trip.latestDriverLocation.longitude, label: "Latest vehicle location" } : null} driverRecordedAt={trip.latestDriverLocation?.recordedAt} driverAccuracyMeters={trip.latestDriverLocation?.accuracyMeters} /></section>

          {(driverHoldEligible.includes(trip.status) || failedAttemptEligible.includes(trip.status)) ? <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setModal({ type: "HOLD", remarks: "", eventAt: toLocalInput(new Date().toISOString()) })} disabled={pendingAction}>Request hold</Button><Button variant="destructive" onClick={() => setModal({ type: "FAILED", remarks: "", eventAt: toLocalInput(new Date().toISOString()) })} disabled={pendingAction}>Report failed attempt</Button></div> : null}
        </div>

        <aside className="space-y-4 lg:sticky lg:top-6 lg:self-start">
          <details className="surface-card group" open><summary className="flex cursor-pointer list-none items-center justify-between p-5 text-sm font-semibold">Trip and equipment details <ChevronDown className="h-4 w-4 transition-transform group-open:rotate-180" /></summary><dl className="space-y-4 border-t border-border p-5 text-sm"><Detail label="Container" value={trip.containerNumber} /><Detail label="Truck" value={trip.truckAssetCode} /><Detail label="EIR reference" value={trip.eirNumber} /><Detail label="Booking reference" value={trip.bookingNumber} /><Detail label="Shipping line" value={trip.shippingLine} /></dl></details>
          <section className="surface-soft p-4"><p className="flex items-center gap-2 text-sm font-semibold"><Truck className="h-4 w-4 text-primary" />Assigned vehicle</p><p className="mt-2 text-xs text-muted-foreground">{trip.truckAssetCode ?? "No truck assigned"}</p></section>
        </aside>
      </div>

      {nextAction ? <div className="fixed inset-x-0 bottom-0 z-30 border-t border-border bg-card/95 p-3 backdrop-blur md:hidden" style={{ paddingBottom: "max(0.75rem, env(safe-area-inset-bottom))" }}><Button className="h-12 w-full" disabled={pendingAction} onClick={() => void submitAction(nextAction.endpoint)}><Navigation className="h-5 w-5" />{pendingAction ? "Updating…" : nextAction.label}</Button></div> : null}

      {modal ? <ExceptionDialog modal={modal} pending={pendingAction} onClose={() => setModal(null)} onSubmit={(remarks) => { const endpoint = modal.type === "HOLD" ? "request-hold" : "report-failure"; setModal(null); void submitAction(endpoint, remarks); }} /> : null}
    </div>
  );
}

function StopTimeline({ stop, label, current, completed }: { stop: DispatchTripDetail["stops"][number] | null; label: string; current: boolean; completed: boolean }) {
  const status = completed ? "Completed" : current ? "Current stop" : "Upcoming";
  return <div className="relative flex gap-3"><div className={`mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-full ${completed ? "bg-emerald-500 text-white" : current ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{completed ? <CheckCircle2 className="h-4 w-4" /> : <MapPin className="h-4 w-4" />}</div><div className="min-w-0 border-b border-border pb-5 last:border-b-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-foreground">{label}</p><span className="text-xs text-muted-foreground">{status}</span></div><p className="mt-1 text-sm text-foreground">{stop?.locationText ?? "Location not specified"}</p><p className="mt-2 flex items-center gap-1.5 text-xs text-muted-foreground"><Clock className="h-3.5 w-3.5" />{stop?.actualAt ? `Arrived ${formatDateTime(stop.actualAt)}` : `Scheduled ${formatDateTime(stop?.scheduledAt)}`}</p></div></div>;
}

function DocumentRow({ type, state, hint, canUpload, pending, isNative, documentUrl, isWaybill, onUpload, inputRef, onFile }: { type: TripDocumentType; state: string; hint: string | null; canUpload: boolean; pending: boolean; isNative: boolean; documentUrl?: string | null; isWaybill: boolean; onUpload: () => void; inputRef: (element: HTMLInputElement | null) => void; onFile: (file: File) => void }) {
  const stateTone = state === "VERIFIED" || state === "READY" ? "text-emerald-700 dark:text-emerald-300" : state === "REJECTED" ? "text-destructive" : state === "MISSING" ? "text-amber-700 dark:text-amber-300" : "text-primary";
  return <div className="flex flex-col gap-3 rounded-2xl border border-border p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-foreground">{formatDocumentLabel(type)}</p><p className={`mt-1 text-xs font-medium ${stateTone}`}>{formatDocumentStateLabel(state as "MISSING" | "UPLOADED" | "VERIFIED" | "REJECTED" | "PENDING" | "READY")}</p>{hint ? <p className="mt-1 text-xs text-muted-foreground">{hint}</p> : null}</div><div className="flex flex-wrap gap-2">{documentUrl ? <Button variant="outline" size="sm" onClick={() => window.open(documentUrl, "_blank", "noopener,noreferrer")}><Eye className="h-4 w-4" />View</Button> : null}{isWaybill ? <Button variant="outline" size="sm" onClick={() => window.print()}><Eye className="h-4 w-4" />View</Button> : null}{canUpload ? <><Button variant="outline" size="sm" className="h-10" disabled={pending} onClick={onUpload}>{isNative ? <Camera className="h-4 w-4" /> : <FileUp className="h-4 w-4" />}{isNative ? "Capture photo" : documentUrl ? "Replace" : "Upload"}</Button><input ref={inputRef} type="file" accept="image/*,.pdf" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) onFile(file); event.currentTarget.value = ""; }} /></> : null}</div></div>;
}

function Detail({ label, value }: { label: string; value?: string | null }) { return <div><dt className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{label}</dt><dd className="mt-1 font-medium text-foreground">{value ?? "Not specified"}</dd></div>; }

function ExceptionDialog({ modal, pending, onClose, onSubmit }: { modal: Exclude<ActionModal, null>; pending: boolean; onClose: () => void; onSubmit: (remarks: string) => void }) {
  const [remarks, setRemarks] = useState(modal.remarks);
  const title = modal.type === "HOLD" ? "Request a trip hold" : "Report a failed attempt";
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby="exception-title" className="w-full max-w-md rounded-3xl border border-border bg-card p-6 shadow-card"><h2 id="exception-title" className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">Dispatch will be notified. Explain what happened before submitting this exception.</p><label className="mt-5 block text-sm font-medium" htmlFor="exception-remarks">Remarks</label><textarea id="exception-remarks" className="mt-2 min-h-[110px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm" value={remarks} onChange={(event) => setRemarks(event.target.value)} autoFocus /><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Cancel</Button><Button variant="destructive" disabled={pending || !remarks.trim()} onClick={() => onSubmit(remarks.trim())}>{pending ? "Submitting…" : "Confirm report"}</Button></div></div></div>;
}
