// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NVGInventory.Data;

#nullable disable

namespace NVGInventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260305114703_AddAuditLogContextFields")]
    partial class AddAuditLogContextFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NVGInventory.Domain.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("current_step");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("workflow_key");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowKey");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("approvals", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.ApprovalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("acted_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ApprovalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approval_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("decision");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("remarks");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ApprovalId");

                    b.ToTable("approval_actions", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("PlateNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("plate_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.ToTable("assets", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("before_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("trace_id");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TripId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("audit_logs", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.AuthEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("auth_method");

                    b.Property<string>("ClientApp")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("client_app");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Environment")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("environment");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MfaMethod")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("mfa_method");

                    b.Property<bool>("MfaPerformed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("mfa_performed");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("reason_code");

                    b.Property<string>("RolesSnapshotJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("roles_snapshot_json");

                    b.Property<string>("SessionId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenJti")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("token_jti");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.HasIndex("Outcome");

                    b.HasIndex("UserId");

                    b.HasIndex("Username");

                    b.ToTable("auth_events", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("inventory_adjustments", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryAdjustmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("InventoryAdjustmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_adjustment_id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<decimal>("QtyDelta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_delta");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("remarks");

                    b.HasKey("Id");

                    b.HasIndex("InventoryAdjustmentId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("InventoryAdjustmentId", "InventoryId")
                        .IsUnique();

                    b.ToTable("inventory_adjustment_lines", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("average_cost");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsKit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_kit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("item_type");

                    b.Property<decimal?>("LastCost")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("last_cost");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("quantity");

                    b.Property<decimal?>("ReorderLevel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("reorder_level");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemType");

                    b.HasIndex("Name");

                    b.ToTable("inventory", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.KitComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("notes");

                    b.Property<decimal>("RequiredQty")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("required_qty");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("InventoryItemId", "Name")
                        .IsUnique();

                    b.ToTable("kit_components", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("BorrowerUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("borrower_user_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("BorrowerUserId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Status", "IssuedAt")
                        .IsDescending(false, true);

                    b.ToTable("loans", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.LoanLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_id");

                    b.Property<decimal>("QtyIssued")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_issued");

                    b.Property<decimal>("QtyReturned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_returned");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("LoanId");

                    b.ToTable("loan_lines", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.LoanLineReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("return_condition");

                    b.Property<Guid>("LoanLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("loan_line_id");

                    b.Property<string>("MissingComponentsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("missing_components_json");

                    b.Property<decimal>("QtyReturned")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_returned");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("received_by_user_id");

                    b.Property<DateTime>("ReturnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("returned_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("LoanLineId");

                    b.HasIndex("ReceivedByUserId");

                    b.ToTable("loan_line_returns", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.ModuleSetting", b =>
                {
                    b.Property<string>("ModuleKey")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("module_key");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("ModuleKey");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("module_settings", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("received_at");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("purchase_orders", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("QtyOrdered")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_ordered");

                    b.Property<decimal>("QtyReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("qty_received");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("PurchaseOrderId", "InventoryId")
                        .IsUnique();

                    b.ToTable("purchase_order_lines", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrderReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_order_line_id");

                    b.Property<decimal>("QtyReceivedIncrement")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_received_increment");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("received_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderLineId");

                    b.HasIndex("ReceivedByUserId");

                    b.ToTable("purchase_order_receipts", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("issued_at");

                    b.Property<string>("Purpose")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("purpose");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("request_type");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("RequestType", "Status");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("requests", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.RequestLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<decimal?>("QtyApproved")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_approved");

                    b.Property<decimal>("QtyRequested")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_requested");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_lines", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "InventoryOfficer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HeadOfFinance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Driver"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dispatcher"
                        });
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.StockLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<string>("MetaJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("meta_json");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("movement_type");

                    b.Property<decimal>("QtyDelta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("qty_delta");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ref_type");

                    b.Property<decimal?>("TotalCostSnapshot")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_cost_snapshot");

                    b.Property<decimal?>("UnitCostSnapshot")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("unit_cost_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("InventoryId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("RefType", "RefId");

                    b.HasIndex("RefType", "RefId", "InventoryId", "MovementType")
                        .IsUnique()
                        .HasFilter("[ref_type] = 'request' AND [movement_type] IN ('OUT', 'BORROW')");

                    b.ToTable("stock_logs", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("suppliers", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Workflow", b =>
                {
                    b.Property<string>("WorkflowKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("workflow_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.HasKey("WorkflowKey");

                    b.ToTable("workflows", "dbo");

                    b.HasData(
                        new
                        {
                            WorkflowKey = "MAINTENANCE_ISSUE_APPROVAL",
                            IsActive = true,
                            Name = "Maintenance Issue Approval"
                        },
                        new
                        {
                            WorkflowKey = "BORROW_APPROVAL",
                            IsActive = true,
                            Name = "Borrow Approval"
                        },
                        new
                        {
                            WorkflowKey = "ADJUSTMENT_APPROVAL",
                            IsActive = true,
                            Name = "Adjustment Approval"
                        },
                        new
                        {
                            WorkflowKey = "PO_APPROVAL",
                            IsActive = true,
                            Name = "PO Approval"
                        });
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("required_role");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("step_order");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("workflow_key");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowKey", "StepOrder")
                        .IsUnique();

                    b.ToTable("workflow_steps", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d4e1f9f-8e90-46a6-9d91-566a1e3b1d01"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "InventoryOfficer",
                            StepOrder = 1,
                            WorkflowKey = "MAINTENANCE_ISSUE_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("1cf3b1a4-f741-4e0c-9c64-57f2a9aa1c02"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "Manager",
                            StepOrder = 2,
                            WorkflowKey = "MAINTENANCE_ISSUE_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("39d4f82f-4ed3-4bfa-91a9-ffcb28e1a103"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "InventoryOfficer",
                            StepOrder = 1,
                            WorkflowKey = "BORROW_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("6d49fedd-f2af-4fd0-89ae-1e1bb9c8c204"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "Manager",
                            StepOrder = 2,
                            WorkflowKey = "BORROW_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("f2eb4a0f-3195-40cd-9050-5b7b9352e705"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "InventoryOfficer",
                            StepOrder = 1,
                            WorkflowKey = "ADJUSTMENT_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("8e6f8b8e-6a64-4f4f-8b78-5d7dd6eb8706"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "Manager",
                            StepOrder = 2,
                            WorkflowKey = "ADJUSTMENT_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("1b6e7c02-8132-4f2f-b53b-8db168a5e407"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "Manager",
                            StepOrder = 1,
                            WorkflowKey = "PO_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("a9f0f9ce-c8c9-47aa-8a71-427f1a6d2b08"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "HeadOfFinance",
                            StepOrder = 2,
                            WorkflowKey = "PO_APPROVAL"
                        },
                        new
                        {
                            Id = new Guid("b9bb7d7d-b2f0-4bb2-91b5-50f2c8188909"),
                            CreatedAt = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequiredRole = "CEO",
                            StepOrder = 3,
                            WorkflowKey = "PO_APPROVAL"
                        });
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<string>("Contact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("dispatch_customers", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("DriverUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_user_id");

                    b.Property<string>("HoldPreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("hold_previous_status");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("notes");

                    b.Property<bool>("PodPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("pod_pending");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TruckAssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("truck_asset_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TruckAssetId");

                    b.HasIndex("DriverUserId", "Status");

                    b.ToTable("dispatch_trips", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.TripDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rejected_by_user_id");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("state");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("SupersedesDocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("supersedes_document_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("doc_type");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("RejectedByUserId");

                    b.HasIndex("SupersedesDocumentId");

                    b.HasIndex("TripId");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("VerifiedByUserId");

                    b.HasIndex("TripId", "Type", "IsActive");

                    b.ToTable("dispatch_trip_documents", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.TripStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("EventAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("event_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("STATUS_CHANGE")
                        .HasColumnName("event_type");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("from_status");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Remarks")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("remarks");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("to_status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "EventAt");

                    b.HasIndex("TripId", "RecordedAt");

                    b.ToTable("dispatch_trip_status_history", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("LocationText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("location_text");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("StopType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("stop_type");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "StopType", "ScheduledAt");

                    b.ToTable("dispatch_trip_stops", "dbo");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Approval", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.ApprovalAction", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.Approval", "Approval")
                        .WithMany("Actions")
                        .HasForeignKey("ApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Approval");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.AuthEvent", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryAdjustmentLine", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.InventoryAdjustment", "InventoryAdjustment")
                        .WithMany("Lines")
                        .HasForeignKey("InventoryAdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryAdjustment");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.KitComponent", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("KitComponents")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Loan", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.Asset", "Asset")
                        .WithMany("Loans")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NVGInventory.Domain.Entities.User", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.Request", "Request")
                        .WithOne("Loan")
                        .HasForeignKey("NVGInventory.Domain.Entities.Loan", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Borrower");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.LoanLine", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.Loan", "Loan")
                        .WithMany("Lines")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.LoanLineReturn", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.LoanLine", "LoanLine")
                        .WithMany("Returns")
                        .HasForeignKey("LoanLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoanLine");

                    b.Navigation("ReceivedBy");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.ModuleSetting", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrderReceipt", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany("Receipts")
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrderLine");

                    b.Navigation("ReceivedBy");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Request", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.Asset", "Asset")
                        .WithMany("Requests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NVGInventory.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.RequestLine", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("RequestLines")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.Request", "Request")
                        .WithMany("Lines")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.StockLog", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("StockLogs")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.Trip", b =>
                {
                    b.HasOne("NVGInventory.Modules.Dispatching.Entities.Customer", "Customer")
                        .WithMany("Trips")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NVGInventory.Domain.Entities.Asset", "TruckAsset")
                        .WithMany()
                        .HasForeignKey("TruckAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("TruckAsset");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.TripDocument", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NVGInventory.Modules.Dispatching.Entities.TripDocument", "SupersedesDocument")
                        .WithMany()
                        .HasForeignKey("SupersedesDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NVGInventory.Modules.Dispatching.Entities.Trip", "Trip")
                        .WithMany("Documents")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Domain.Entities.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RejectedBy");

                    b.Navigation("SupersedesDocument");

                    b.Navigation("Trip");

                    b.Navigation("UploadedBy");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.TripStatusHistory", b =>
                {
                    b.HasOne("NVGInventory.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NVGInventory.Modules.Dispatching.Entities.Trip", "Trip")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.TripStop", b =>
                {
                    b.HasOne("NVGInventory.Modules.Dispatching.Entities.Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Approval", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryAdjustment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("KitComponents");

                    b.Navigation("RequestLines");

                    b.Navigation("StockLogs");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Loan", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.LoanLine", b =>
                {
                    b.Navigation("Returns");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Request", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("NVGInventory.Domain.Entities.Workflow", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.Customer", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("NVGInventory.Modules.Dispatching.Entities.Trip", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("StatusHistory");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
