using System.Globalization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NVGInventory.Contracts;
using NVGInventory.Data;
using NVGInventory.Domain.Constants;
using NVGInventory.Domain.Services;
using NVGInventory.Modules.Dispatching.Entities;
using NVGInventory.Modules.Dispatching.Enums;
using NVGInventory.Modules.Dispatching.Services;
using NVGInventory.Security;

namespace NVGInventory.Modules.Dispatching.Controllers;

[ApiController]
[Route("api/dispatch")]
[Authorize]
public sealed class DispatchRecommendationController : ControllerBase
{
    private readonly InventoryDbContext _dbContext;
    private readonly ITripChainingSuggestionService _suggestionService;
    private readonly IAuditService _auditService;
    private readonly ITripLifecycleService _tripLifecycleService;

    public DispatchRecommendationController(
        InventoryDbContext dbContext,
        ITripChainingSuggestionService suggestionService,
        IAuditService auditService,
        ITripLifecycleService tripLifecycleService)
    {
        _dbContext = dbContext;
        _suggestionService = suggestionService;
        _auditService = auditService;
        _tripLifecycleService = tripLifecycleService;
    }

    [HttpPost("trip-chaining/trips/{tripId:guid}/suggestions")]
    [HttpPost("trips/{tripId:guid}/recommendations")]
    [Authorize(Roles = $"{RoleNames.Dispatcher},{RoleNames.Manager},{RoleNames.Admin},{RoleNames.SuperAdmin}")]
    public async Task<ActionResult<IReadOnlyCollection<TripChainingSuggestionResponse>>> GenerateSuggestions(
        Guid tripId,
        CancellationToken cancellationToken)
    {
        await _suggestionService.GenerateSuggestionsAsync(tripId, cancellationToken);
        var recommendations = await LoadPendingQuery(DateTime.UtcNow)
            .Where(recommendation => recommendation.CompletedTripId == tripId)
            .ToListAsync(cancellationToken);

        return Ok(recommendations.Select(MapSuggestion).ToList());
    }

    [HttpGet("trip-chaining/pending")]
    [HttpGet("recommendations/pending")]
    [Authorize(Roles = $"{RoleNames.Dispatcher},{RoleNames.Manager},{RoleNames.Admin},{RoleNames.SuperAdmin},{RoleNames.Driver}")]
    public async Task<ActionResult<IReadOnlyCollection<TripChainingSuggestionResponse>>> GetPendingSuggestions(
        CancellationToken cancellationToken)
    {
        var now = DateTime.UtcNow;
        // Reading the queue must never rerun CSP-TOPSIS. Suggestions are generated by
        // operational events or the explicit generation endpoint, then expire normally.
        var rawRecs = await LoadPendingQuery(now)
            .OrderByDescending(r => r.GeneratedAt)
            .ThenBy(r => r.Rank)
            .ToListAsync(cancellationToken);

        var suggestions = rawRecs
            .GroupBy(r => new { r.CompletedTripId, r.RecommendedTripId })
            .Select(g => g.First())
            .OrderByDescending(r => r.GeneratedAt)
            .ThenBy(r => r.Rank)
            .ToList();

        return Ok(suggestions.Select(MapSuggestion).ToList());
    }

    [HttpPost("trip-chaining/suggestions/{id:guid}/confirm")]
    [HttpPost("recommendations/{id:guid}/accept")]
    [Authorize(Roles = $"{RoleNames.Dispatcher},{RoleNames.Manager},{RoleNames.Admin},{RoleNames.SuperAdmin}")]
    public async Task<ActionResult<TripChainingSuggestionResponse>> ConfirmSuggestion(
        Guid id,
        CancellationToken cancellationToken)
    {
        var now = DateTime.UtcNow;
        var recommendation = await _dbContext.DispatchRecommendations
            .FirstOrDefaultAsync(item => item.Id == id, cancellationToken);
        if (recommendation is null)
        {
            return NotFound("Trip chaining suggestion not found.");
        }

        if (recommendation.ExpiresAt < now)
        {
            return Conflict("Trip chaining suggestion has expired.");
        }

        if (recommendation.WasAccepted || recommendation.WasIgnored)
        {
            return Conflict("Trip chaining suggestion was already reviewed.");
        }

        var actorUserId = User.GetUserId();
        recommendation.WasAccepted = true;
        recommendation.ReviewedByUserId = actorUserId;
        recommendation.ReviewedAt = now;

        var recommendedTrip = await _dbContext.DispatchTrips
            .Include(t => t.Stops)
            .FirstOrDefaultAsync(t => t.Id == recommendation.RecommendedTripId, cancellationToken);
        if (recommendedTrip is null)
        {
            return NotFound("Suggested next movement not found.");
        }

        var pickupStop = recommendedTrip.Stops.FirstOrDefault(s => s.StopType == TripStopType.Pickup);
        var dropoffStop = recommendedTrip.Stops.FirstOrDefault(s => s.StopType == TripStopType.Dropoff);

        var basePickupTime = (pickupStop?.ScheduledAt.HasValue == true && pickupStop.ScheduledAt.Value > now)
            ? pickupStop.ScheduledAt.Value
            : now.AddMinutes(30);

        if (pickupStop != null)
        {
            pickupStop.ScheduledAt = basePickupTime;
        }

        if (dropoffStop != null)
        {
            dropoffStop.ScheduledAt = basePickupTime.AddHours(1);
        }

        var siblingRecommendations = await _dbContext.DispatchRecommendations
            .Where(item =>
                (item.CompletedTripId == recommendation.CompletedTripId || item.RecommendedTripId == recommendation.RecommendedTripId) &&
                item.Id != recommendation.Id &&
                !item.WasAccepted &&
                !item.WasIgnored)
            .ToListAsync(cancellationToken);
        foreach (var sibling in siblingRecommendations)
        {
            sibling.WasIgnored = true;
            sibling.ReviewedByUserId = actorUserId;
            sibling.ReviewedAt = now;
        }

        _auditService.AddEntry(
            actorUserId,
            AuditActions.RecommendationAccepted,
            EntityTypes.DispatchRecommendation,
            recommendation.Id,
            null,
            new
            {
                RecommendationId = recommendation.Id,
                recommendation.RecommendedTripId,
                recommendation.CompletedTripId
            },
            tripId: recommendation.RecommendedTripId);

        var completedTrip = await _dbContext.DispatchTrips
            .AsNoTracking()
            .FirstOrDefaultAsync(t => t.Id == recommendation.CompletedTripId, cancellationToken);

        var driverUserId = completedTrip?.DriverUserId ?? recommendation.DriverId;

        var dispatchCommand = new DispatchTripCommand(
            recommendation.RecommendedTripId,
            driverUserId,
            recommendation.TruckId,
            "Confirmed through Trip Chaining",
            recommendedTrip.RowVersion);

        var actorContext = BuildActor();

        await _tripLifecycleService.DispatchAsync(dispatchCommand, actorContext, cancellationToken);
        await _dbContext.SaveChangesAsync(cancellationToken);

        var loaded = await LoadRecommendationById(id, cancellationToken);
        return Ok(MapSuggestion(loaded!));
    }

    [HttpPost("trip-chaining/suggestions/{id:guid}/dismiss")]
    [HttpPost("recommendations/{id:guid}/ignore")]
    [Authorize(Roles = $"{RoleNames.Dispatcher},{RoleNames.Manager},{RoleNames.Admin},{RoleNames.SuperAdmin}")]
    public async Task<IActionResult> Ignore(
        Guid id,
        CancellationToken cancellationToken)
    {
        var recommendation = await _dbContext.DispatchRecommendations
            .FirstOrDefaultAsync(item => item.Id == id, cancellationToken);
        if (recommendation is null)
        {
            return NotFound("Trip chaining suggestion not found.");
        }

        if (!recommendation.WasAccepted && !recommendation.WasIgnored)
        {
            var actorUserId = User.GetUserId();
            recommendation.WasIgnored = true;
            recommendation.ReviewedByUserId = actorUserId;
            recommendation.ReviewedAt = DateTime.UtcNow;

            _auditService.AddEntry(
                actorUserId,
                AuditActions.RecommendationIgnored,
                EntityTypes.DispatchRecommendation,
                recommendation.Id,
                null,
                new
                {
                    RecommendationId = recommendation.Id,
                    recommendation.RecommendedTripId,
                    recommendation.CompletedTripId
                },
                tripId: recommendation.RecommendedTripId);

            await _dbContext.SaveChangesAsync(cancellationToken);
        }

        return Ok();
    }

    [HttpGet("trip-chaining/history")]
    [HttpGet("recommendations/history")]
    [Authorize(Roles = $"{RoleNames.Dispatcher},{RoleNames.Manager},{RoleNames.Admin},{RoleNames.SuperAdmin},{RoleNames.Ceo}")]
    public async Task<ActionResult<PagedResult<TripChainingSuggestionResponse>>> GetHistory(
        [FromQuery] string? from,
        [FromQuery] string? to,
        [FromQuery] int? page,
        [FromQuery] int? pageSize,
        CancellationToken cancellationToken)
    {
        if (!TryResolveDateRange(from, to, out var fromUtc, out var toUtc, out var dateError))
        {
            return BadRequest(dateError);
        }

        if (!TryResolvePaging(page, pageSize, out var resolvedPage, out var resolvedPageSize, out var pagingError))
        {
            return BadRequest(pagingError);
        }

        var query = LoadBaseQuery()
            .Where(recommendation => recommendation.WasAccepted || recommendation.WasIgnored);
        if (fromUtc.HasValue)
        {
            query = query.Where(recommendation => recommendation.GeneratedAt >= fromUtc.Value);
        }

        if (toUtc.HasValue)
        {
            query = query.Where(recommendation => recommendation.GeneratedAt <= toUtc.Value);
        }

        var totalCount = await query.CountAsync(cancellationToken);
        var items = await query
            .OrderByDescending(recommendation => recommendation.GeneratedAt)
            .ThenBy(recommendation => recommendation.Rank)
            .Skip((resolvedPage - 1) * resolvedPageSize)
            .Take(resolvedPageSize)
            .ToListAsync(cancellationToken);

        return Ok(new PagedResult<TripChainingSuggestionResponse>(
            items.Select(MapSuggestion).ToList(),
            totalCount,
            resolvedPage,
            resolvedPageSize));
    }

    private IQueryable<DispatchRecommendation> LoadPendingQuery(DateTime now)
    {
        return LoadBaseQuery()
            .Where(recommendation =>
                recommendation.ExpiresAt > now &&
                !recommendation.WasAccepted &&
                !recommendation.WasIgnored &&
                recommendation.RecommendedTrip.Status == TripStatus.Draft);
    }

    private IQueryable<DispatchRecommendation> LoadBaseQuery()
    {
        return _dbContext.DispatchRecommendations
            .Include(recommendation => recommendation.CompletedTrip)
                .ThenInclude(trip => trip.Driver)
            .Include(recommendation => recommendation.CompletedTrip)
                .ThenInclude(trip => trip.TruckAsset)
            .Include(recommendation => recommendation.CompletedTrip)
                .ThenInclude(trip => trip.Stops)
            .Include(recommendation => recommendation.CompletedTrip)
                .ThenInclude(trip => trip.StatusHistory)
            .Include(recommendation => recommendation.RecommendedTrip)
                .ThenInclude(trip => trip.Stops)
            .Include(recommendation => recommendation.ReviewedByUser)
            .AsSplitQuery();
    }

    private async Task<DispatchRecommendation?> LoadRecommendationById(
        Guid id,
        CancellationToken cancellationToken)
    {
        return await LoadBaseQuery()
            .FirstOrDefaultAsync(recommendation => recommendation.Id == id, cancellationToken);
    }

    private static TripChainingSuggestionResponse MapSuggestion(DispatchRecommendation recommendation)
    {
        var completedTrip = recommendation.CompletedTrip;
        var recommendedTrip = recommendation.RecommendedTrip;
        var currentLocation = completedTrip.Status == TripStatus.Delivered
            ? completedTrip.Stops.LastOrDefault(stop => stop.StopType == TripStopType.Dropoff)?.LocationText
            : completedTrip.Stops
                .Where(stop => stop.ActualAt.HasValue)
                .OrderByDescending(stop => stop.ActualAt)
                .Select(stop => stop.LocationText)
                .FirstOrDefault()
              ?? completedTrip.Stops.FirstOrDefault(stop => stop.StopType == TripStopType.Pickup)?.LocationText;
        var recommendedPickup = recommendedTrip.Stops
            .FirstOrDefault(stop => stop.StopType == TripStopType.Pickup)
            ?.LocationText;
        var recommendedDropoff = recommendedTrip.Stops
            .FirstOrDefault(stop => stop.StopType == TripStopType.Dropoff)
            ?.LocationText;
        var availableAt = completedTrip.StatusHistory
            .Where(history => history.ToStatus == TripStatus.Delivered || history.ToStatus == TripStatus.Cancelled)
            .OrderByDescending(history => history.EventAt)
            .Select(history => (DateTime?)history.EventAt)
            .FirstOrDefault();
        var agingHours = Math.Max(0, (DateTime.UtcNow - recommendedTrip.CreatedAt).TotalHours);

        var suitabilityReasons = BuildSuitabilityReasons(recommendedTrip, recommendedPickup, recommendedDropoff);
        var warnings = BuildOperationalWarnings(recommendedTrip);
        availableAt ??= completedTrip.UpdatedAt;

        return new TripChainingSuggestionResponse(
            recommendation.Id,
            recommendation.Rank,
            recommendation.Rank == 1,
            suitabilityReasons,
            warnings,
            new CurrentMovementResponse(
                completedTrip.Id,
                recommendation.DriverId,
                recommendation.TruckId,
                completedTrip.Driver?.Username ?? "Unassigned driver",
                completedTrip.TruckAsset?.AssetCode ?? completedTrip.TruckAsset?.PlateNo ?? "Unassigned truck",
                currentLocation ?? string.Empty,
                completedTrip.Status == TripStatus.Delivered ? "Delivery completed" : "Trip cancelled",
                availableAt),
            new NextMovementResponse(
                recommendedTrip.Id,
                recommendedTrip.ContainerNumber,
                recommendedPickup ?? string.Empty,
                recommendedDropoff ?? string.Empty,
                recommendedTrip.ContainerSize,
                recommendedTrip.TripType,
                recommendedTrip.Stops
                    .Where(stop => stop.StopType == TripStopType.Pickup)
                    .Select(stop => stop.ScheduledAt)
                    .FirstOrDefault(),
                Math.Round(agingHours, 2)),
            recommendation.ExpiresAt,
            recommendation.GeneratedAt,
            recommendation.WasAccepted,
            recommendation.WasIgnored,
            recommendation.ReviewedByUser?.Username,
            recommendation.ReviewedAt);
    }

    private static IReadOnlyCollection<string> BuildSuitabilityReasons(
        Trip trip,
        string? pickupLocation,
        string? dropoffLocation)
    {
        var reasons = new List<string>
        {
            "Assignment check passed for this driver and truck."
        };

        if (!string.IsNullOrWhiteSpace(pickupLocation) && !string.IsNullOrWhiteSpace(dropoffLocation))
        {
            reasons.Add("The route can follow the current movement and reduce empty return travel.");
        }

        var pickupAt = trip.Stops
            .Where(stop => stop.StopType == TripStopType.Pickup)
            .Select(stop => stop.ScheduledAt)
            .FirstOrDefault();
        if (pickupAt.HasValue && pickupAt.Value > DateTime.UtcNow)
        {
            reasons.Add("The pickup schedule is still achievable.");
        }

        if (!string.IsNullOrWhiteSpace(trip.ContainerSize))
        {
            reasons.Add("The truck meets the movement's equipment requirement.");
        }

        return reasons;
    }

    private static IReadOnlyCollection<string> BuildOperationalWarnings(Trip trip)
    {
        var warnings = new List<string>();
        var pickupAt = trip.Stops
            .Where(stop => stop.StopType == TripStopType.Pickup)
            .Select(stop => stop.ScheduledAt)
            .FirstOrDefault();

        if (!pickupAt.HasValue)
        {
            warnings.Add("Confirm the pickup time before dispatch.");
        }
        else if (pickupAt.Value <= DateTime.UtcNow)
        {
            warnings.Add("The pickup time will be refreshed when this next movement is confirmed.");
        }

        if (string.IsNullOrWhiteSpace(trip.ContainerNumber))
        {
            warnings.Add("Set the container number before dispatch.");
        }

        return warnings;
    }

    private DispatchActorContext BuildActor()
    {
        return new DispatchActorContext(
            User.GetUserId(),
            User.IsInRole(RoleNames.Manager),
            User.IsInRole(RoleNames.Dispatcher),
            User.IsInRole(RoleNames.Driver),
            User.IsInRole(RoleNames.HeadOfFinance),
            User.IsInRole(RoleNames.Ceo),
            User.IsInRole(RoleNames.Admin) || User.IsInRole(RoleNames.SuperAdmin));
    }

    private static bool TryResolveDateRange(
        string? from,
        string? to,
        out DateTime? fromUtc,
        out DateTime? toUtc,
        out string? error)
    {
        fromUtc = null;
        toUtc = null;

        if (!TryParseUtcDate(from, out fromUtc, out error))
        {
            return false;
        }

        if (!TryParseUtcDate(to, out toUtc, out error))
        {
            return false;
        }

        if (fromUtc.HasValue && toUtc.HasValue && fromUtc > toUtc)
        {
            error = "'from' must be earlier than or equal to 'to'.";
            return false;
        }

        error = null;
        return true;
    }

    private static bool TryResolvePaging(
        int? page,
        int? pageSize,
        out int resolvedPage,
        out int resolvedPageSize,
        out string? error)
    {
        resolvedPage = page.GetValueOrDefault(1);
        if (resolvedPage < 1)
        {
            error = "Page must be at least 1.";
            resolvedPageSize = 0;
            return false;
        }

        resolvedPageSize = pageSize.GetValueOrDefault(20);
        if (resolvedPageSize < 1 || resolvedPageSize > 100)
        {
            error = "Page size must be between 1 and 100.";
            return false;
        }

        error = null;
        return true;
    }

    private static bool TryParseUtcDate(string? raw, out DateTime? parsed, out string? error)
    {
        parsed = null;
        error = null;

        if (string.IsNullOrWhiteSpace(raw))
        {
            return true;
        }

        if (!DateTimeOffset.TryParse(raw, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var value))
        {
            error = "Invalid date value.";
            return false;
        }

        parsed = value.UtcDateTime;
        return true;
    }
}

public sealed record TripChainingSuggestionResponse(
    Guid SuggestionId,
    int SelectionOrder,
    bool IsRecommended,
    IReadOnlyCollection<string> SuitabilityReasons,
    IReadOnlyCollection<string> Warnings,
    CurrentMovementResponse CurrentMovement,
    NextMovementResponse NextMovement,
    DateTime ExpiresAt,
    DateTime GeneratedAt,
    bool WasAccepted,
    bool WasIgnored,
    string? ReviewedBy,
    DateTime? ReviewedAt);

public sealed record CurrentMovementResponse(
    Guid TripId,
    Guid DriverId,
    Guid TruckId,
    string DriverName,
    string TruckPlate,
    string CurrentLocation,
    string AvailabilityReason,
    DateTime? AvailableAt);

public sealed record NextMovementResponse(
    Guid TripId,
    string? ContainerNumber,
    string PickupLocation,
    string DropoffLocation,
    string? ContainerSize,
    string? TripType,
    DateTime? ScheduledPickupTime,
    double AgingHours);
